#!/usr/bin/python3

import sys
import subprocess
import os

def pdf():
    print('Rotate?')
    ans = input('> ')

    print('Converting PDF to PNG...')
    subprocess.run(['pdftoppm', '-png', f'{sys.argv[1]}', f'{sys.argv[2]}'])
    print('Done')
    print()

    if ans and ans.lower()[0] == 'y':
       print('Rotating images...')
       os.system(f'for i in {sys.argv[2]}*.png; do convert -rotate "90" "$i" "$i"; done;')
       print('Done')
       print()

    print('Reading files with Tesseract...')
    os.system(f'for i in {sys.argv[2]}*.png; do tesseract "$i" "text-$i" -l eng; done;')
    print()
    print('Done')

    os.system(f'cat text-{sys.argv[2]}* > {sys.argv[2]}.txt')

    # clean up files
    print()
    print('Cleaning files...')
    os.system(f'rm {sys.argv[2]}*.png')
    os.system(f'rm text-{sys.argv[2]}*.txt')
    print('Done')
    print()

    return f'{sys.argv[2]}.txt'

def main():
    if len(sys.argv) != 3:
        print('ocr [file] [save-file]')
        print("Please provide two arguments.")
        sys.exit()

    if sys.argv[1][-3:] == 'pdf':
        file = pdf()
        print(f"Saved to {file}")
    else:
        print("File must be a PDF")

if __name__ == '__main__':
    main()
