#!/usr/bin/python3

# sanitize: sanitize text input from stdin
#   1. join hyphenated words separated by new line
#   2. remove parenthesis/brackets
#   3. remove repeated characters
#   4. remove special characters
#   5. make all lowercase

import re
import sys


lines=sys.stdin.read().splitlines()

joined = ''

# join words separated by hyphen and newline
END_JOIN = '−-–—'

for line in lines:
    if line and line[-1] in END_JOIN:
        joined += line[:-1]
    else:
        joined += line + ' '

# remove dates (references/citation)
date_rx = "\([^\(\)]*\d\d+?[^\(\)]*\)"
#           ([not parenthesis]* [number][number]+ [not parenthesis]*)

joined = re.sub(date_rx, ' ', joined)

# removed repeated characters
joined = re.sub(r'([^\w][^\w]+)\1', ' ', joined)

# remove special characters
joined = re.sub(r'\s?[^\.?!,;:\-\w\s]\s', ' ', joined)

# remove trailing whitespace
joined = joined.strip()

# all lowercase
joined = joined.lower()

print(joined, end='')
