#!/usr/bin/python3

# sanitize: sanitize text input from stdin
#   1. join hyphenated words separated by new line
#   2. remove parenthesis/brackets
#   3. remove repeated characters
#   4. remove special characters
#   5. make all lowercase

import re
import sys


def main():
    try:
        lines = sys.stdin.read().splitlines()
    except:
        exit()

    joined = ""

    # join words separated by hyphen and newline
    END_JOIN = "−-–—"

    for line in lines:
        if not line.strip():
            continue
        if line[-1] in END_JOIN:
            joined += line[:-1]
        else:
            joined += line + " "

    # remove dates (references/citation)
    date_rx = "\([^\(\)]*\d\d+?[^\(\)]*\)"
    #           ([not parenthesis]* [number][number]+ [not parenthesis]*)

    # remove academic citations
    citation_rx = "\[[^\[\]]*\d\d+?[^\[\]]*\]"
    #               ([not bracket]* [number][number]+ [not bracket]*)

    joined = re.sub(date_rx, " ", joined)
    joined = re.sub(citation_rx, " ", joined)

    # remove special characters
    joined = re.sub(r"\s?[^\.?!,;:\-\w\s\[\]\(\)]\s", " ", joined)

    # removed repeated characters
    joined = re.sub(r"([^A-Za-z0-9])(\1+)", r"\1", joined)
    joined = re.sub(r"([^A-Za-z0-9]+)(\1+)", r"\1", joined)
    joined = re.sub(r"(\s)\s", r"\1", joined)

    # remove trailing whitespace
    joined = joined.strip()

    # all lowercase
    joined = joined.lower()

    print(joined, end="")


if __name__ == "__main__":
    main()
