#!/bin/bash

# screenreader: ocr -> tts

set -e

SPEED=1.1

OCR_DIR="/tmp/screenreader-tts"
MP3_DIR="/tmp/screenreader-tts/mp3"

mkdir -p $OCR_DIR
mkdir -p $MP3_DIR

datern=`date +"%Y-%m-%d_%T"`
img_filename=`date +"screenreader-$datern"`
tts_filename=`date +"tts-$datern"`

# gnome
# gnome-screenshot -a -f $OCR_DIR/$img_filename.png || exit 1

# xfce
xfce4-screenshooter -r -s "$OCR_DIR"/"$img_filename.png" || exit 1

if ! [ -f "$OCR_DIR"/"$img_filename".png ]; then
    exit
fi

# teseract saves $img_filename as .txt
tesseract -l eng "$OCR_DIR"/"$img_filename.png" "$OCR_DIR"/"$img_filename"

notify-send -u critical -t 0 -i "$HOME/.icons/tts.png" "screenreader" "Generating text to speech..."

# mimic3
cat "$OCR_DIR"/"$img_filename".txt | sanitize | mimic3 --voice en_US/vctk_low#p276 > "$MP3_DIR"/"$tts_filename".mp3

# kill notification
pkill xfce4-notifyd

# kill existing process
PID=`pgrep -f --list-full mpv | grep "$MP3_DIR" | awk '{print $1}'`
echo $PID
! [[ -z $PID ]] && kill $PID

mpv \
    --ontop \
    --autofit="10%" \
    --geometry="0%:100%" \
    --force-window \
    --keep-open="always" \
    --cover-art-files="$HOME/.icons/tts_bg.png" \
    --speed=$SPEED \
    "$MP3_DIR"/"$tts_filename".mp3