#!/bin/bash

# screenreader: rudimentary screen reader using tesseract and mimic3

OCR_DIR="/tmp/screenreader-tts"
MP3_DIR="/tmp/screenreader-tts/mp3"

mkdir -p $OCR_DIR
mkdir -p $MP3_DIR

datern=`date +"%Y-%m-%d_%T"`
img_filename=`date +"screenreader-$datern"`
tts_filename=`date +"tts-$datern"`

# gnome
# gnome-screenshot -a -f $OCR_DIR/$img_filename.png

# xfce
xfce4-screenshooter -r -s "$OCR_DIR"/"$img_filename.png"

# teseract saves $img_filename as .txt
tesseract -l eng "$OCR_DIR"/"$img_filename.png" "$OCR_DIR"/"$img_filename"

cat "$OCR_DIR"/"$img_filename".txt | tr '[:upper:]' '[:lower:]' | mimic3 --voice en_US/vctk_low#p276 > "$MP3_DIR"/"$tts_filename".mp3

mpv \
    --ontop \
    --autofit="10%" \
    --geometry="0%:100%" \
    --force-window \
    --keep-open="always" \
    --cover-art-files="$HOME/.icons/tts_bg.png" \
    "$MP3_DIR"/"$tts_filename".mp3