#!/usr/bin/python3

import os
import time
import re
import threading

import tkinter
from tkinter import *
from tkinter.filedialog import askopenfilename
import pdftotext

# global variables
current_pdf = ""
currentPage = 1
pageCount = 0
reading = False
speed = 1

# GUI
root = Tk()
root.title('TTS')
root.geometry("1400x800")

# menu
menu = Menu(root)
root.config(menu=menu)

# clear page
def clear_page(event=None):
    text.delete(1.0, tkinter.END)

# update page count
def update_page():
    page_format = f'{currentPage}'
    page_box.delete(1.0, tkinter.END)
    page_box.insert(1.0, page_format)

    count_format = f'/{pageCount}'
    count_box.delete(1.0, tkinter.END)
    count_box.insert(1.0, count_format)

# open file
def open_file(event=None):
    global current_pdf
    global pageCount
    global currentPage
    filelocation = askopenfilename(initialdir="~", title="Select PDF",
            filetypes=(
                ("PDF Files", "*.pdf"),
                ("TXT Files", "*.txt"),
                ("All Files", "*.*")))

    if filelocation[-3:] == "txt":
        with open(filelocation, "r") as f:
            current_txt = f.read()

            currentPage = 1
            pageCount = 1
            text.delete(1.0, tkinter.END)
            text.insert(1.0, current_txt)
            update_page()

    elif filelocation[-3:] == "pdf":
        with open(filelocation, "rb") as f:
            current_pdf = pdftotext.PDF(f)

            currentPage = 1
            pageCount = len(current_pdf)
            pdf_text = current_pdf[currentPage-1]
            text.delete(1.0, tkinter.END)
            text.insert(1.0, pdf_text)
            update_page()

# previous page function
def prevPage(event=None):
    global current_pdf
    global currentPage
    if currentPage > 1:
        currentPage -= 1
        pdf_text = current_pdf[currentPage-1]
        text.delete(1.0, tkinter.END)
        text.insert(1.0, pdf_text)
        update_page()
    else:
        pass

# next page function
def nextPage(event=None):
    global current_pdf
    global currentPage
    global pageCount
    if currentPage < pageCount:
        currentPage += 1
        pdf_text = current_pdf[currentPage-1]
        text.delete(1.0, tkinter.END)
        text.insert(1.0, pdf_text)
        update_page()

# speed control
def speed_control(val):
    global speed
    speed = val

# wrapper for read_aloud
def read_aloud_background(event=None):
    global reading
    if not reading:
        reading = True
        t = threading.Thread(target=read_aloud)
        t.start()
    elif reading:
        reading = False

# read contents
def read_aloud():
    global reading
    save_file = "/tmp/tts_read_file.mp3"
    idx = '1.0'
    lastidx = '1.0'

    current_text = text.get('1.0', tkinter.END+"-1c")
    if current_text:
        # split sentences
        groups = re.split('[\.!?]\s', current_text)
        for sentence in groups:
            if sentence.lstrip().rstrip() and reading:
                for line in re.split('[\n\t\r]', sentence):
                    idx = text.search(line, lastidx, stopindex=tkinter.END)
                    lastidx = f'{str(idx)}+{len(line)}c'

                    # set tag to highlight current passage
                    text.tag_add('current', idx, lastidx)

                    # increment line
                    idx = float(idx) + 1

                # highlight current passage
                text.tag_config('current', background='lightblue')

                # update position
                idx = lastidx

                # pre-sanitize
                print(sentence)

                # sanitize quotes, brackets, parentheses, hyphen, colon, semicolon
                sentence = re.sub('[\[\]\{\}\(\)\-:;_*]', '', sentence)
                sentence = re.sub("[“”’]", '', sentence)
                sentence = re.sub('"', '', sentence)

                # replace all white space with space
                sentence = re.sub('\s', ' ', sentence)

                # post-sanitize
                print(sentence)

                # gtts-cli (alternative: espeak)
                if os.path.exists(save_file):
                    os.system(f'rm {save_file}')
                os.system(f'gtts-cli -l en "{sentence}" > {save_file}')
                while not os.path.exists(save_file):
                    pass

                # play passage
                os.system(f'mpv --speed={speed} {save_file}')

                # remove highlight
                text.tag_config('current', background='')

                # remove tags
                for tag in text.tag_names():
                    text.tag_delete(tag)

    reading = False

# jump to page
def jump_text(event=None):
    global current_pdf
    global currentPage
    global pageCount
    current_page = int(page_box.get(1.0, tkinter.END))
    if current_page:
        if current_page <= pageCount and currentPage >= 1:
            currentPage = current_page
            pdf_text = current_pdf[currentPage-1]
            text.delete(1.0, tkinter.END)
            text.insert(1.0, pdf_text)
            update_page()
    else:
        pass


# buttons
button_frame = Frame(root)
button_frame.pack(fill=tkinter.X, side=tkinter.TOP)

prev_page_button = Button(button_frame, text="Prev", command=prevPage, bg="pink")
next_page_button = Button(button_frame, text="Next", command=nextPage, bg="lightblue")

read_page_button = Button(button_frame, text="Read", command=read_aloud_background, bg="lightgreen")
jump_page_button = Button(button_frame, text="Jump", command=jump_text, bg="orange")

button_frame.columnconfigure(0, weight=1)
button_frame.columnconfigure(1, weight=1)
button_frame.columnconfigure(2, weight=1)
button_frame.columnconfigure(3, weight=1)

prev_page_button.grid(row=0, column=0, sticky=tkinter.W+tkinter.E)
next_page_button.grid(row=0, column=1, sticky=tkinter.W+tkinter.E)
read_page_button.grid(row=0, column=2, sticky=tkinter.W+tkinter.E)
jump_page_button.grid(row=0, column=3, sticky=tkinter.W+tkinter.E)

# page box
page_frame = Frame(root)
page_frame.pack(side=tkinter.TOP)

page_box = Text(page_frame, height=1, width=5)
count_box = Text(page_frame, height=1, width=5)

page_frame.columnconfigure(0, weight=1)
page_frame.columnconfigure(1, weight=1)

page_box.grid(row=0, column=0, sticky=tkinter.W+tkinter.E)
count_box.grid(row=0, column=1, sticky=tkinter.W+tkinter.E)

# speed slider
speed_slider = Scale(root, from_=0, to=3, digits=3, length=250, resolution=0.25, orient=HORIZONTAL, command=speed_control)
speed_slider.pack()
speed_slider.set(1)

# textbox
text = Text(root, height=1000, width=1000, font=("Arial", 15))
text.pack()

# keybinds
root.bind('<Control-o>', open_file)
root.bind('<Control-l>', clear_page)
root.bind('<Control-Left>', prevPage)
root.bind('<Control-Right>', nextPage)
root.bind('<Control-r>', read_aloud_background)
root.bind('<Control-j>', jump_text)

# dropdowns
file_menu = Menu(menu, tearoff=False)
menu.add_cascade(label="File", menu=file_menu)
file_menu.add_command(label="Open PDF", command=open_file)
file_menu.add_command(label="Clear", command=clear_page)
file_menu.add_separator()
file_menu.add_command(label="Exit", command=root.quit)

root.mainloop()
