#!/usr/bin/python3

import time
import sys
import os
import re

import subprocess
from rich.progress import track
from gtts import gTTS

def pdf():
    print('Rotate?')
    ans = input('> ')

    print('Converting PDF to PNG...')
    subprocess.run(['pdftoppm', '-png', f'{sys.argv[1]}', f'{sys.argv[2]}'])
    print('Done')
    print()

    if ans and ans.lower()[0] == 'y':
       print('Rotating images...')
       os.system(f'for i in {sys.argv[2]}*.png; do convert -rotate "90" "$i" "$i"; done;')
       print('Done')
       print()

    print('Reading files with Tesseract...')
    os.system(f'for i in {sys.argv[2]}*.png; do tesseract "$i" "text-$i" -l eng; done;')
    print()
    print('Done')

    os.system(f'cat text-{sys.argv[2]}* > {sys.argv[2]}.txt')

    # clean up files
    print()
    print('Cleaning files...')
    os.system(f'rm {sys.argv[2]}*.png')
    os.system(f'rm text-{sys.argv[2]}*.txt')
    print('Done')
    print()

    return f'{sys.argv[2]}.txt'

def tts(file):
    to_delete = (file != sys.argv[1])

    print(f'Reading from "{file}"')
    with open(file, 'r') as f:
        text = f.read()
        text = re.sub(' +', ' ', text)
        text = text.split('.')

    n = 0
    for sentence in track(text, description='Saving to file'):
        sentence.strip()
        sentence.replace('"#$%&()*+, -./:;<=>@[\]^_`{|}~', '')
        if sentence:
            try:
                tts = gTTS(text=sentence, lang="en")
                tts.save(f'{sys.argv[2]}{n}.mp3')

                with open('mp3.txt', 'a') as f:
                    f.write(f"file '{sys.argv[2]}{n}.mp3'\n")

                time.sleep(1)
                n += 1
            except:
                pass
        else:
            pass

    subprocess.run(['ffmpeg', '-f', 'concat', '-safe', '0', '-i', 'mp3.txt', '-loglevel', 'quiet', '-c', 'copy', f'TTS_{sys.argv[2]}.mp3'])

    # delete temporary files
    os.system(f'rm -rf {sys.argv[2]}*.mp3')
    if to_delete:
        os.system(f'rm -rf {file}')
    subprocess.run(['rm', 'mp3.txt'])

    print()
    print('Complete!')
    print(f'Saved to "{sys.argv[2]}.mp3"')

def main():
    if len(sys.argv) != 3:
        print('tts [file] [save-file]')
        print("Please provide two arguments.")
        sys.exit()

    if sys.argv[1][-3:] == 'pdf':
        file = pdf()
        tts(file)
    elif sys.argv[1][-3:] == 'txt':
        tts(sys.argv[1])
    else:
        print('File must be either PDF or TXT.')

if __name__ == '__main__':
    main()
